server:
  port: 8080

spring:
  application:
    name: tacticore-backend
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
      enabled: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

# Configuraciones de simulación ML
simulation:
  enabled: false
  json-directory: demos-jsons

# Configuración del servicio ML
ml:
  service:
    url: http://3.91.78.196:8000
    file-param-name: demo_file
